### ISSUE TITLE
Cursor Line Number Color not working as yellow

### ISSUE THREAD

**Issue by gautampanchal94** [ofirgall/ofirkai.nvim#18]
I am using Alacritty Termianl with neovim 0.8. I want to change Cursor Line Number color, but it seems it's not working.

![Screenshot](https://user-images.githubusercontent.com/86514804/207929563-331d3f1c-0318-4585-8e66-5de7dce5bb5c.png)

**Comment by ofirgall** [comment]
Can you share your setup of `ofirkai`?

**Comment by gautampanchal94** [comment]
I have used packer for installing.
![ScreenShot](https://user-images.githubusercontent.com/86514804/208134515-3d79d5b2-8e67-42fd-844f-60709ac9271a.png)

I have tried to change LineNr but it changes all LineNumber color.

**Comment by ofirgall** [comment]
You need to override `CursorLineNr` instead.

**Comment by gautampanchal94** [comment]
Still Not working!
![2022-12-17 19 26 43](https://user-images.githubusercontent.com/86514804/208245468-3441156e-af01-40c1-8587-13705ad95432.png)

**Comment by gautampanchal94** [comment]
Tried it not working!

**Comment by ofirgall** [comment]
![image](https://user-images.githubusercontent.com/4954051/208376333-d9479722-35e6-4332-88d9-468873855378.png)
Works on my machine, can you try to upgrade your nvim?

**Comment by gautampanchal94** [comment]
I tried it still not working. Maybe there is some other issue.

Thank you for your help.

**Comment by gautampanchal94** [comment]
Okay. Thank you for this.
