### ISSUE TITLE
Is 100% feel and look like ST4 allowed?

### ISSUE THREAD

**Issue by MainEditor** [ofirgall/ofirkai.nvim#19]
I'm noticed this cool colorscheme don't highlights a \\ in a strings in Lua files like ST4 does it. In python files all look good.
**Screenshot**
![Снимок экрана 2022-12-20 180302](https://user-images.githubusercontent.com/98752769/208673899-8d132a41-0c7e-4473-b766-833b29552123.png)

**Comment by ofirgall** [comment]
The tree-sitter parser of Lua (or vimscript, I'm not sure if `cmd` is embedding vimscript or not) doesn't parse `\\` as `@string.escape` so it won't get colored, you need to open an issue to the [vimscript](https://github.com/vigoux/tree-sitter-viml)/[Lua](https://github.com/MunifTanjim/tree-sitter-lua) tree parser repo.

You can test it with `:TSHighlightCapturesUnderCursor` that come from [nvim-treesitter/playground](https://github.com/nvim-treesitter/playground).

**Comment by MainEditor** [comment]
Oh OK, sorry I'm don't know about that
