### ISSUE TITLE
Styling discrepancies ofirkai vs sublime-text 4

### ISSUE THREAD

**Issue by yetyetanotherusername** [ofirgall/ofirkai.nvim#24]
First off, thank you for this excellent theme, this is the closest to sublime's own monokai that I've seen anyone get.

I noticed that there are a few subtle differences in coloring of keywords, function definitions asf (see screenshots). Being completely unknowledgeable about customizing/theming/highlighting in neovim I have to ask: Is this a conscious decision/treesitter thing/a setting I missed/forced by some other aspect outside of your control or are these simply bugs? If it's the first, then so be it, it's still an excellent theme, but if it is the latter, i'd like to perhaps offer my help in fixing them.

sublime
![image](https://user-images.githubusercontent.com/15213889/222676761-05424b32-c8e4-4bf3-b2b0-bcdf2eeacb9a.png)

neovim/ofirkai
![image](https://user-images.githubusercontent.com/15213889/222677027-f7beb201-6907-47c9-919d-f7b31611c340.png)

**Comment by ofirgall** [comment]
Hey, I'm glad you enjoy the theme. There are some discrepancies, some due personal preferences some due how treesitter works, you can always customize your own highlight groups on top of ofirkai.

**Comment by yetyetanotherusername** [comment]
That's what I thought, thanks for confirming!

**Comment by yetyetanotherusername** [comment]
For reference, I'll add my custom highlight groups here if anybody stumbles across this issue. I've tested this with `python` and the only discrepancies left I could find was the `@` operator being blue in decorators and the `pass` keyword being blue as well.

```lua
local scheme = require("ofirkai").scheme
require('ofirkai').setup({
  custom_hlgroups = {
        ['@constant'] = {
      fg = scheme.aqua,
    },
        ['@function'] = {
      fg = scheme.green,
    },
        ['@keyword'] = {
      fg = scheme.aqua,
    },
        ['@keyword.function'] = {
      fg = scheme.aqua,
    },
        ['@method'] = {
      fg = scheme.green,
    },
  }
})

```
