### ISSUE TITLE
Add highlight for WinSeparator

### ISSUE THREAD

**Issue by fingolfin19** [ofirgall/ofirkai.nvim#27]
Nvim is deprecating VertSplit and moving to WinSeparator in 0.10. By default, WinSeparator links to normal which does not look great for most colorschemes.

**Comment by ofirgall** [comment]
Hey, thanks for the issue. I'm not familiar with WinSeparator and unfortunately I don't have much spare time to test it on a new neovim. Will linking WinSeparator to VertSplit do the job?

**Comment by fingolfin19** [comment]
> Hey, thanks for the issue. I'm not familiar with WinSeparator and unfortunately I don't have much spare time to test it on a new neovim. Will linking WinSeparator to VertSplit do the job?

I believe the new default scheme avoided doing it that way since VertSplit is being deprecated, but I also see quite a few colorscheme authors linking to VertSplit anyhow. I'm not sure what the long term implications might be, but short term I'd guess it will be fine.  It should also work to just copy VertSplit and change it to WinSeparator.

**Comment by ofirgall** [comment]
I linked to VertSplit for now, if it would cause any trouble I'll copy the values instead. Let me know if there is any issues, thanks.
