### ISSUE TITLE
remove_italics doesn't seem to work

### ISSUE THREAD

**Issue by harshavb** [ofirgall/ofirkai.nvim#28]
I tried setting `remove_italics` in my configuration file like so:
```lua
return {
  --[[
  {
    'morhetz/gruvbox',
    priority = 1000,
    init = function()
      vim.cmd.colorscheme 'gruvbox'
    end
  }
  --]]
  {
    'ofirgall/ofirkai.nvim',
    priority = 1000,

    config = function()
      require('ofirkai').setup {
        remove_italics = true
      }
    end,

    init = function()
      vim.cmd.colorscheme 'ofirkai'
    end
  }
}
```
It doesn't seem to work though:

![image](https://github.com/user-attachments/assets/2f791f51-277e-4b07-b020-403555345bc1)

**Comment by ofirgall** [comment]
`vim.cmd.colorscheme` in `init` is overriding the setup on `config`. You can remove the init function
